# Generated by Django 4.2.7 on 2023-11-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_alter_redactor_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='published_date',
            field=models.DateField(auto_now=True),
        ),
    ]
