# Generated by Django 4.2.7 on 2023-11-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0004_remove_newspaper_redactors_newspaper_redactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
